### ISSUE TITLE
/drustcraft reports information on the Drustcraft Engine in use

### ISSUE THREAD

**Issue by ProjectHSI** [Drustcraft/engine#104]
### What feature do you want to see added?

/drustcraft is currently not allowed to be executed by other users by default, perhaps something could appear like
Version: 2.0.3
Citizens: ✔️
Denizen: ✔️
_List goes on for all recommended plugins that are strictly required for full functionality_
and perhaps some other information in there as well.

**Comment by nomadjimbob** [comment]
There is a "/drustcraft version" which lists all that information. I will check the permissions when I can as there is no problem with that info being public

**Comment by ProjectHSI** [comment]
copy. i just noticed that code in core.dsc
