### ISSUE TITLE
API Endpoint /query to return numbers with fractional components.

### ISSUE THREAD

**Issue by ProjectHSI** [Drustcraft/engine#111]
### What feature do you want to see added?

see /mspt for the discord bot and title.

**Comment by nomadjimbob** [comment]
The endpoint returns the average MSPT over the last 5 seconds as a decimal. I believe that is enough information for an end user.

The current Discord Bot displays the MSPT for each tick over the last 5 seconds as it has direct access to that information. If a user requires that fine detail of server performance, than they would need console access anyway and can obtain that kind of detail there.

**Comment by ProjectHSI** [comment]
I am a fool for not checking 5secs later lol, just saw that info.

**Comment by nomadjimbob** [comment]
It is all good. No issues double checking things are how they should.

There is a lot of documentation missing which doesn't help. I am working on updating that ASAP!

**Comment by ProjectHSI** [comment]
alright.
