### ISSUE TITLE
'Main' branch action automatically publishes all commits to the production Evalyn server, and *not* the development version

### ISSUE THREAD

**Issue by ProjectHSI** [Drustcraft/engine#113]
### Describe the bug

The main branch action upon commiting to this repo publishes all changes to the production server, regardless of it's not ready for production, perhaps publish to a development server instead?

### Screenshots / Videos

![Screenshot 2022-04-30 110748](https://user-images.githubusercontent.com/57279339/166084603-97720791-970a-4039-9040-022177e26931.png)

**Comment by nomadjimbob** [comment]
I did that push manually to fix a critical bug in 2.0.5
