### ISSUE TITLE
ChatGUI could be better in console

### ISSUE THREAD

**Issue by nomadjimbob** [Drustcraft/engine#76]
### Describe the bug

Currently the following issues are displayed when using ChatGUI in console:

- Buttons are displayed, but not clickable!
- When a list has no items, nothing is displayed as a result in the console

### To Reproduce

Above

### Expected behaviour

Fixed

**Comment by ProjectHSI** [comment]
First problem is **unfixable** due to the way terminals are handled.

**Comment by nomadjimbob** [comment]
It is fixable thou as the engine dictates what is outputted. At the moment it assumes it is in-game which is incorrect when chatgui is used for a command and run from console
